In [28]:
import requests
from bs4 import BeautifulSoup
import pandas as pd

In [29]:
url = "https://www.ccny.cuny.edu/registrar/fall"
r = requests.get(url)

In [30]:
soup = BeautifulSoup(r.text,"html.parser")
table = soup.find("table")
rows = table.find_all("tr")
data = []

for row in rows[1:]:
    cols = row.find_all("td")
    if len(cols) >= 3:
        date = cols[0].get_text(strip=True)
        dow  = cols[1].get_text(strip=True)
        text = cols[2].get_text(strip=True)
        data.append([date, dow, text])
print(data[:3])

[['August 01', 'Sunday', 'Application for degree for January and February 2022 begins'], ['August 18', 'Wednesday', 'Last day to apply for Study Abroad'], ['August 24', 'Tuesday', 'Last day of Registration;Last day to file ePermit for the Fall 2021;Last day to drop classes for 100% tuition refund;']]

In [31]:
df = pd.DataFrame(data, columns=["date", "dow", "text"])
df.head()

,date,dow,text
0,August 01,Sunday,Application for degree for January and Februar...
1,August 18,Wednesday,Last day to apply for Study Abroad
2,August 24,Tuesday,Last day of Registration;Last day to file ePer...
3,August 25,Wednesday,Start of Fall Term;Classes begin;Initial Regis...
4,August 25 - 31,Wednesday - Tuesday,Change of program period; late fees apply

In [32]:
def parse_date(date_str):
    date_str = date_str.split("-")[0].strip()
    date_str = date_str + " 2021"
    return pd.to_datetime(date_str)

df["date"] = df["date"].apply(parse_date)
df.head()

,date,dow,text
0,2021-08-01,Sunday,Application for degree for January and Februar...
1,2021-08-18,Wednesday,Last day to apply for Study Abroad
2,2021-08-24,Tuesday,Last day of Registration;Last day to file ePer...
3,2021-08-25,Wednesday,Start of Fall Term;Classes begin;Initial Regis...
4,2021-08-25,Wednesday - Tuesday,Change of program period; late fees apply

In [33]:
df = df.set_index("date")
df.head()

print(df.to_string(max_colwidth=100))

                                      dow                                                                                                 text
date
2021-08-01 00:00:00                Sunday                                          Application for degree for January and February 2022 begins
2021-08-18 00:00:00             Wednesday                                                                   Last day to apply for Study Abroad
2021-08-24 00:00:00               Tuesday  Last day of Registration;Last day to file ePermit for the Fall 2021;Last day to drop classes for...
2021-08-25 00:00:00             Wednesday                                 Start of Fall Term;Classes begin;Initial Registration Appeals begin;
2021-08-25 00:00:00   Wednesday - Tuesday                                                            Change of program period; late fees apply
2021-08-26 00:00:00              Thursday                                                                       Last day for Independent Study
2021-08-28 00:00:00              Saturday                                                                        First day of Saturday Classes
2021-08-31 00:00:00               Tuesday  Last day to add a class to an existing enrollment;Last day for 75% tuition refund;Financial Aid ...
2021-09-01 00:00:00             Wednesday  Verification of Enrollment rosters available to faculty;Course Withdrawal drop period begins (A ...
2021-09-03 00:00:00    Friday - Wednesday                                                                                 No classes scheduled
2021-09-06 00:00:00                Monday                                                      College Closed;Last day for 50% tuition refund;
2021-09-09 00:00:00              Thursday                                                                                 Freshman Convocation
2021-09-14 00:00:00               Tuesday  Last day for 25% tuition refund;Census date;Last day to change or declare a major/minor to be ef...
2021-09-15 00:00:00             Wednesday  Assignment of 'WN' grades for non-attendance;Course Withdrawal period begins (A grade of 'W' is ...
2021-09-15 00:00:00  Wednesday - Thursday                                                                                 No classes scheduled
2021-09-23 00:00:00              Thursday                                          Last day to submit proof of immunization for NYS residents;
2021-09-24 00:00:00                Friday                                            Assignment of 'WA' grades for immunization non-compliance
2021-10-01 00:00:00                Friday                                               Advising month begins for Spring and Winter enrollment
2021-10-08 00:00:00                Friday  Deadline for filing application for degree for January and February 2022;Last day to submit proo...
2021-10-11 00:00:00                Monday                                                                                       College Closed
2021-11-01 00:00:00                Monday  'INC' grades for Spring 2021 and Winter 2021 for Undergraduate students convert to 'FIN';'INC' g...
2021-11-02 00:00:00               Tuesday  Registration appointments for Winter and Spring 2022 begin for continuing students.  Check your ...
2021-11-04 00:00:00              Thursday                                                                     Last day to file for P/NC option
2021-11-06 00:00:00              Saturday                                                                                 60% Date of the term
2021-11-23 00:00:00               Tuesday                             'INC' grades for Summer 2021 for Undergraduate students convert to 'FIN'
2021-11-25 00:00:00     Thursday - Sunday                                                                                       College Closed
2021-12-11 00:00:00              Saturday                                                                         Last day of Saturday Classes
2021-12-13 00:00:00                Monday  Course Withdrawal period ends (Last day to withdraw from a class with the grade of 'W');Last day...
2021-12-14 00:00:00               Tuesday                                                                                          Reading Day
2021-12-15 00:00:00   Wednesday - Tuesday                                                                                   Final Examinations
2021-12-21 00:00:00               Tuesday                                                                                          End of Term
2021-12-24 00:00:00     Friday - Saturday                                                                                       College Closed
2021-12-27 00:00:00                Monday                                                                                       College Closed
2021-12-28 00:00:00               Tuesday                                                        Final Grade Submission Deadline for Fall 2021
2021-12-31 00:00:00                Friday                                                                                       College Closed
2022-01-01 20:21:00              Saturday                                                      College Closed;Fall 2021 Degree Conferral Date;